name: DevSoutinho
repository: https://github.com/devsoutinho/flutter-labs

# Where are the packages being required in this project?
packages:
  - libs/**
  - products/**
  - shells/**

# ???
command:
  bootstrap:
    usePubspecOverrides: true
  version:
      updateGitTagRefs: true # defaults to false

# What are the handfull scripts that you need in this monorepo?
scripts:
  hello: echo 'Hello World'
  ## CI Scripts
  lint:
    exec: dart analyze .
  test:
    run: melos run test:selective_unit_test --no-select
    description: Run all Flutter tests in this project.
  gen_coverage: melos exec -- "\$MELOS_ROOT_PATH/scripts/combineCoverage.sh"
  ## Web Scripts
  build_shell_webportal: "cd ./shells/web_portal && flutter build web --web-renderer html"
  deploy_web: "cd ./shells/web_portal && npx vercel ./build/web --confirm --token=$VERCEL_TOKEN"
  deploy_web_prod: "cd ./shells/web_portal && npx vercel ./build/web --confirm --token=$VERCEL_TOKEN --prod"
  preview_web: "cd ./scripts && node ./pullRequestPreview.js --experimental-fetch"
  ## Support Scripts
  test:selective_unit_test:
    run: melos exec --dir-exists="test" --fail-fast -- flutter test --no-pub --coverage
    description: Run Flutter tests for a specific package in this project.
    select-package:
      flutter: true
      dir-exists: test
  create_product:
    description: Allow you to create a new product
    run: "cd products && flutter create"
# References
# - https://medium.com/flutter-community/managing-multi-package-flutter-projects-with-melos-c8ce96fa7c82
