name: DevSoutinho
repository: https://github.com/devsoutinho/flutter-labs

# Where are the packages being required in this project?
packages:
  - apps/**
  - libs/**

# ???
command:
  bootstrap:
    usePubspecOverrides: true

# What are the handfull scripts that you need in this monorepo?
scripts:
  hello: echo 'Hello World'
  analyze:
    exec: dart analyze .
