name: DevSoutinho
repository: https://github.com/devsoutinho/flutter-labs

# Where are the packages being required in this project?
packages:
  - libs/**
  - products/**
  - shells/**

# ???
command:
  bootstrap:
    usePubspecOverrides: true

# What are the handfull scripts that you need in this monorepo?
scripts:
  hello: echo 'Hello World'
  analyze:
    exec: dart analyze .
  build_shell_webportal: "cd ./shells/web_portal && flutter build web --web-renderer html"
  deploy_web: "cd ./shells/web_portal && npx vercel ./build/web --confirm --token=$VERCEL_TOKEN"
  deploy_web_prod: "cd ./shells/web_portal && npx vercel ./build/web --confirm --token=$VERCEL_TOKEN --prod"
  preview_web: "cd ./scripts && node ./pullRequestPreview.js --experimental-fetch"
