name: CD - Flutter Web

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: devsoutinho/flutter-composite-action@v4.0.1
    - name: Build & Deploy
      run: |
          melos bootstrap
          melos test
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: devsoutinho/flutter-composite-action@v4.0.1
    - name: Build & Deploy
      run: |
          melos bootstrap
          melos lint
  deploy_web:
    needs: 
      - test
      - lint
    runs-on: ubuntu-latest
    steps:
    - uses: devsoutinho/flutter-composite-action@v4.0.1
    - name: Build & Deploy
      run: |
        melos bootstrap
        # melos build_shell_webportal
        # melos deploy_web_prod
