name: CI - Web

on:
  pull_request:
    types: [opened, synchronize]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  deploy_preview:
    runs-on: ubuntu-latest
    steps:
    ## [Common_CI_Steps]
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v2
      with:
        node-version: 18
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.4'
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    ## ======
    - run: dart pub global activate melos
    - run: |
        melos bootstrap
        melos build_shell_webportal
        melos preview_web
