name: CD - Flutter Web

on:
  push:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.4'
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: dart pub global activate melos
    - run: |
        melos bootstrap
        melos build_shell_webportal
        melos deploy_web_prod
