name: PR comment
on:
  issue_comment:                                     
    types: [created, edited, deleted]

env:
  GH_TOKEN: ${{ secrets.GH_TOKENS }}

jobs:
  comment_checker:
    # if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
    runs-on: ubuntu-latest
    permissions:
        issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: devsoutinho/flutter-composite-action@v4.0.1
      
      - name: "[RELEASE-beta X.0.0]"
        if: contains(github.event.comment.body, '!release-beta')   # check the comment if it contains the keywords
        run: |
          melos bootstrap
          # git config --global user.email "13791385+omariosouto@users.noreply.github.com"
          # git config --global user.name "CI Bot - DevSoutinho"
          echo "kkkkkkkkkkkkkk"
          echo "${{github.event.label.name}}"
          echo "kkkkkkkkkkkkkk"
          melos version --prerelease --preid=beta --since=main
      - name: Create comment
        if: contains(github.event.comment.body, '!release-beta')
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: 1
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'

      - name: "[RELEASE-MAJOR X.0.0]"
        if: contains(github.event.comment.body, '!release-major')   # check the comment if it contains the keywords
        run: |
          melos bootstrap
          echo "IMPLEMENT ME"
          ls -la
      - name: "[RELEASE-MINOR 0.X.0]"
        if: contains(github.event.comment.body, '!release-minor')   # check the comment if it contains the keywords
        run: |
          melos bootstrap
          echo "IMPLEMENT ME"
          ls -la
      - name: "[RELEASE-PATCH 0.0.X]"
        if: contains(github.event.comment.body, '!release-patch')   # check the comment if it contains the keywords
        run: |
          melos bootstrap
          echo "IMPLEMENT ME"
          ls -la

